feat: agregue el contenedor para mongodb y configuracion de prettier
martindevaluado/miciudad-api pull request #3
Opened 2021-11-11 17:16 UTC by KenethSandoval

- Configure el archivo de docker-compose para levantar la base de datos y tener un volumen para que persistan los datos.
- Configuracions de prettier para el indentado del codigo.
- Una pequeña documentación de como levantar la base de datos en local con docker.

2021-11-11 22:14 UTC, gonza7aav requested changes
Creo que no se debería incluir el archivo `.env.example` porque está vacío. Preferentemente lo dejaría para un PR que haga uso de las variables de entorno.

También, a mi parecer, seria mejor dejar de lado la configuración de prettier para otro PR, ya que todavía no esta instalado. O en caso de instalarlo, instalar también typescript (si es que se usará) o quitar los plugins correspondientes.

2021-11-12 14:53 UTC, KenethSandoval commented
@gonza7aav listo

2021-11-13 15:22 UTC, gonza7aav approved these changes

2021-12-04 17:44 UTC, merged

2021-12-04 17:45 UTC, martindevaluado commented
Excelente trabajo! Gracias @KenethSandoval @gonza7aav 🤗